apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-reverse-proxy
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
      listen 80;

      {{- range (include "ui-base.renderUpstreams" . | fromYamlArray) }}

      location {{ .path }}/ {

        {{- if .passHostHeader }}
        proxy_set_header Host $host;
        {{- end }}

        proxy_set_header Authorization $http_authorization;

        {{- if .rewriteTarget }}
        rewrite ^{{ .path }}/?(.*)$ {{ .rewriteTarget }}$1 break;
        {{- end }}

        proxy_pass {{ .uri }};
      }

    {{- end }}
    }