apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-reverse-proxy
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
      listen 80;

      {{- range (include "ui-base.renderUpstreams" . | fromYamlArray) }}

      location {{ .path }}/ {

        proxy_ssl_server_name on;

        proxy_http_version 1.1;

        {{- if .websocket }}
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 24h;
        {{- end }}

        {{- if .sse }}
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Connection "";
        proxy_read_timeout 24h;
        {{- end }}

        {{- if .passHostHeader }}
        proxy_set_header Host $host;
        {{- end }}

        proxy_set_header Authorization $http_authorization;

        # IMPORTANT: trailing slash enforces path stripping correctly
        proxy_pass {{ .uri }}/;
      }

    {{- end }}
    }