apiVersion: v2
name: p99
description: P99 UI
type: application
version: 0.5.0 # Bumped by CI job
appVersion: "0.5.0" # Bumped by CI job

dependencies:
  - name: ui-base
    repository: "file://../../../helm/"
    version: 0.1.0
