ui-base:
  name: i15-1
  host: douglas.diamond.ac.uk

  image:
    repository: ghcr.io/douglaswinter/atlas/i15-1
    tag: 0.0.1-auth-manual.18

  upstreams:
    - id: echo
      path: /api/echo
      sse: true
      target:
        service:
          name: echo-server
          port: 8080

    - id: testapi
      path: /api/test
      rewriteTarget: /
      target:
        external:
          uri: https://jsonplaceholder.typicode.com

    - id: blueapi
      path: /api/blueapi
      rewriteTarget: /
      target:
        external:
          uri: https://i15-1-blueapi.diamond.ac.uk

    - id: daq-queue
      path: /api/daq-queue
      rewriteTarget: /
      target:
        external:
          uri: https://i15-1-daq-queue.diamond.ac.uk

    - id: supergraph
      path: /api/graphql
      rewriteTarget: /graphql
      target:
        external:
          uri: https://graph-nightly.diamond.ac.uk
      passHostHeader: false
